### ISSUE TITLE
Fix padding-top from button in profile page

### ISSUE THREAD

**Issue by 1alyciaoliveira** [1alyciaoliveira/TrackYourGoals#65]
![image](https://github.com/1alyciaoliveira/TrackYourGoals/assets/108914238/fe8bf0af-95aa-4776-bad3-ac40e1c744f7)

**Comment by JessFarron** [comment]
Done I ´ll do the back button here. I wasn´t able to get the sign in mails. So I change isVerified to true while working on the app. Return it to flase. Waiting to merge this branch to dev-final. Until we check mail issue
