### ISSUE TITLE
App shouldn't allow negative numbers as target_number

### ISSUE THREAD

**Issue by 1alyciaoliveira** [1alyciaoliveira/TrackYourGoals#71]
Currently, user can remove more money than initially added.

![image](https://github.com/1alyciaoliveira/TrackYourGoals/assets/108914238/b9e02e38-88bd-48f2-9969-1482704ef50a)

**Comment by santis1001** [comment]
![image](https://github.com/1alyciaoliveira/TrackYourGoals/assets/72838881/e382df0a-1f4f-44fb-b09f-0e86b4a8b554)
![image](https://github.com/1alyciaoliveira/TrackYourGoals/assets/72838881/d0e89422-b702-44b4-802f-06d0538c06c3)

Not allowing to push to the database negative goal target, and not removing more than the total amount saved
