### ISSUE TITLE
Nodemailer Error when adding/removing money

### ISSUE THREAD

**Issue by 1alyciaoliveira** [1alyciaoliveira/TrackYourGoals#72]
Im facing an error when adding/removing money using my own account

![image](https://github.com/1alyciaoliveira/TrackYourGoals/assets/108914238/21269144-497f-4775-961c-702b235aa3eb)

**Comment by 1alyciaoliveira** [comment]
TRANSACTION CAN BE DONE, error is only related to nodemailer.

**Comment by santis1001** [comment]
Error related to .emv file
must have EMAIL=``
EMAILPASSWORD=``

**Comment by 1alyciaoliveira** [comment]
that was it
